### ISSUE TITLE
EntitiesWith should not return a vector of pointers

### ISSUE THREAD

**Issue by misnor** [babsnbabs/babs-ecs#23]
Currently we need to execute the following work around when iterating over entities that are returned from EntitiesWith:

```
std::vector<Entity *> entities = this->ecs->EntitiesWith(Graphic(), Position());

for (Entity* entity : entities)
{
	Entity convertedEntity = *entity;
	Graphic position = this->ecs->GetComponent(convertedEntity, Position());
	Graphic graphic = this->ecs->GetComponent(convertedEntity, Graphic());

        // {...}
}
```

Since we want consumers to be able to modify entities, GetComponent needs an overload to accept an Entity pointer instead of requiring consumers to convert it into a non-pointer before use.

**Comment by misnor** [comment]
Alternatively, `EntitiesWith` should not return a pointer to the entities - it just needs to be consistent.

**Comment by jddeal** [comment]
> Alternatively, `EntitiesWith` should not return a pointer to the entities - it just needs to be consistent.

I'd argue for that guy since we don't really need or want entities to be edited by the ECS user. Our entities are tiny and comparable in size to a pointer, so we probably won't see a meaningful performance cost.
