### ISSUE TITLE
Create component specific lists of entities

### ISSUE THREAD

**Issue by jddeal** [babsnbabs/babs-ecs#7]
This is what entityplus is doing to get big performance boosts. The idea is you have the full lists of entities, and then for each component you keep track of entities with that component. When you go to search for entities with component X, you look at the list of entities with component X first, which likely is less than the total list of entities, and thus less to search through, and thus faster to search.

This becomes huge when you have rare components (like AI, or items) that only a dozen entities in the ECS of tens of thousands of entities.

**Comment by misnor** [comment]
Extra note for performance:

Given a search on `EntitiesWith()` with `Identity` and `AI`, assuming there are 1,000 entities, with 900 with Identity and 5 with `AI`, we should start the search on the lowest assigned component first (`AI`) or we will not see most of the performance increase.
